-- AlterTable
ALTER TABLE "User" ADD COLUMN "plan" TEXT NOT NULL DEFAULT 'free',
ADD COLUMN "tokensUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "tokensLastReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
